### ISSUE TITLE
#1791 crash if domogik status changed or network status change

### ISSUE THREAD

**Issue by tikismoke** [domogik/domodroid#4]
Domodroid crash if network status changed.
Historique
#1
Mis à jour par tikismoke il y a presque 2 ans

    Sujet changé de crash if network status changed à crash if domogik status changed

Comment Edit

When domogik became unreachable (ie restaring) domodroid crash, with this sor of log:

11-27 23:30:09.826: E/AndroidRuntime(19336): FATAL EXCEPTION: AsyncTask #4
11-27 23:30:09.826: E/AndroidRuntime(19336): java.lang.RuntimeException: An error occured while executing doInBackground()
11-27 23:30:09.826: E/AndroidRuntime(19336): at android.os.AsyncTask$3.done(AsyncTask.java:299)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.FutureTask.run(FutureTask.java:239)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.lang.Thread.run(Thread.java:856)
11-27 23:30:09.826: E/AndroidRuntime(19336): Caused by: java.lang.NullPointerException
11-27 23:30:09.826: E/AndroidRuntime(19336): at rinor.Events_manager$ListenerThread.doInBackground(Events_manager.java:256)
11-27 23:30:09.826: E/AndroidRuntime(19336): at rinor.Events_manager$ListenerThread.doInBackground(Events_manager.java:1)
11-27 23:30:09.826: E/AndroidRuntime(19336): at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-27 23:30:09.826: E/AndroidRuntime(19336): at java.util.concurrent.FutureTask.run(FutureTask.java:234)
11-27 23:30:09.826: E/AndroidRuntime(19336): ... 3 more

**Comment by tikismoke** [comment]
We need to advise user when mq or tickets from rest are no more available.
